cassandra-rs/cassandra-rs

- .travis.yml
- CONTRIBUTING.md
- Cargo.toml
- README.md
Update repository/code details for fork.
> Fork package

- Cargo.toml
- README.md
Signed-off-by: Keith Wansbrough <Keith.Wansbrough@metaswitch.com>
> Set repo path correctly.

- Cargo.toml
- src/cassandra/cluster.rs
- src/cassandra/error.rs
- src/cassandra/future.rs
- src/cassandra/value.rs
- src/lib.rs
- tests/basic.rs
Fix some warnings and remove some extreme breakage, to make the tests pass.
> Fix warnings

- CONTRIBUTING.md
- README.md
- Remove incorrect project name from contribution guidelines.
- Give container a specific name for convenience.
> Improve docs.

- CONTRIBUTING.md
- README.md
Signed-off-by: Keith Wansbrough <Keith.Wansbrough@metaswitch.com>
> More docs on front page and in contribution guidelines.

- Cargo.toml
- README.md
- build.rs
- examples/schema_meta.rs
- src/cassandra/cluster.rs
- src/cassandra/uuid.rs
- src/lib.rs
- tests/async.rs
- tests/basic.rs
- tests/batch.rs
- tests/bind_by_name.rs
- tests/collections.rs
- tests/help/mod.rs
- tests/maps.rs
- tests/paging.rs
- tests/uuids.rs
Miscellaneous fixes to make this crate ready for publishing.
> Prepare for publish

- README.md
- examples/simple.rs
> Add simple.rs example

- README.md
> Docs can now be found on docs.rs.

- CHANGELOG.md
- Cargo.toml
- README.md
- src/cassandra/batch.rs
- src/cassandra/cluster.rs
- src/cassandra/collection.rs
- src/cassandra/consistency.rs
- src/cassandra/data_type.rs
- src/cassandra/error.rs
- src/cassandra/future.rs
- src/cassandra/iterator.rs
- src/cassandra/log.rs
- src/cassandra/policy/retry.rs
- src/cassandra/prepared.rs
- src/cassandra/result.rs
- src/cassandra/row.rs
- src/cassandra/session.rs
- src/cassandra/ssl.rs
- src/cassandra/statement.rs
- src/cassandra/tuple.rs
- src/cassandra/user_type.rs
- src/cassandra/value.rs
- src/cassandra/write_type.rs
Per the commit logs:
* Bump version, create changelog.
* Add Copy, Clone, Hash for all nullary enums.
* Specify correct Send and Sync markers for all C* types.
> Misc usability fixes

- Cargo.toml
- src/lib.rs
- tests/async.rs
- tests/futures.rs
Signed-off-by: David Hotham <david.hotham@metaswitch.com>
> Remove unused dependencies, update used dependencies

- CHANGELOG.md
- Cargo.toml
> Update to version 0.13.1.

- CHANGELOG.md
> Fill in CHANGELOG date for 0.13.2.

- CHANGELOG.md
- src/cassandra/inet.rs
- src/cassandra/iterator.rs
- src/cassandra/row.rs
- src/cassandra/statement.rs
- src/cassandra/value.rs
- tests/basic.rs
- tests/batch.rs
I found a couple of missing binding types for both `Row` and `Statement`, not sure I should add tests for this though, please advise.
> add missing rust binding types for Row and Statement

- README.md
Signed-off-by: Keith.Wansbrough@metaswitch.com
> Add link to tupshin's old repo

- CHANGELOG.md
- src/cassandra/result.rs
- src/cassandra/row.rs
Signed-off-by: Neil Jensen <neilgithub@jensenet.com>
> Extend the lifetime of a CassResult into a Row

- src/cassandra/result.rs
> Fix trivial comment typo

- CHANGELOG.md
- src/cassandra/data_type.rs
> feat: Expose `new_user_type` on `ConstDataType`

- CHANGELOG.md
- src/cassandra/cluster.rs
> feat: add Cluster::set_token_aware_routing_shuffle_replicas

- Cargo.toml
> chore: upgrade tokio to 1.0

- CHANGELOG.md
- Cargo.toml
- src/cassandra/cluster.rs
- src/cassandra/statement.rs
- src/cassandra/time.rs
- tests/basic.rs
> chore: remove `time` crate

- CHANGELOG.md
- examples/collections.rs
- src/cassandra/collection.rs
- tests/collections.rs
- tests/maps.rs
> 0.16: CassCollection::new -> CassCollection::with_capacity

- .floki/Dockerfile
- CHANGELOG.md
- README.md
- floki.yaml
- src/cassandra/batch.rs
- src/cassandra/custom_payload.rs
- src/cassandra/future.rs
- src/cassandra/session.rs
- src/cassandra/statement.rs
- src/cassandra/value.rs
- src/lib.rs
Signed-off-by: Max Dymond <max.dymond@metaswitch.com>
> Add support for getting custom payloads on executes

- Cargo.toml
Signed-off-by: Keith Wansbrough <Keith.Wansbrough@metaswitch.com>
> Bump forthcoming version to 0.17-pre

- CHANGELOG.md
- Cargo.toml
Bump version and changelog for 0.17.0.
> Release 0.17.0

- Cargo.toml
> Bump to 0.17.1-pre

- src/cassandra/cluster.rs
- src/cassandra/schema/table_meta.rs
- src/cassandra/statement.rs
idk much about unsafe Rust but this fixes the remaining errors I had in https://github.com/Metaswitch/cassandra-rs/issues/116 and I think its right?
> cast to *const c_char instead of *const i8 for pointers

- CHANGELOG.md
- Cargo.toml
Bump version and changelog for 0.17.1.
> Release 0.17.1

- Cargo.toml
> Bump to 0.17.3-pre

- .github/workflows/build.yml
- CHANGELOG.md
- src/cassandra/log.rs
- src/lib.rs
Closes https://github.com/Metaswitch/cassandra-rs/issues/149
I forgot to readd the reexport in lib.rs when I readded it in https://github.com/Metaswitch/cassandra-rs/pull/146
Also added in a few extra changes that I should have done originally.
> Fix set_logger

- CHANGELOG.md
- Cargo.toml
Various back-compatible changes.
Signed-off-by: Keith Wansbrough <Keith.Wansbrough@metaswitch.com>
> Release 1.2.0

- CONTRIBUTING.md
- src/cassandra/result.rs
> Typo fix in src/cassandra/result.rs

- src/cassandra/value.rs
This will fix <error> message when debug/display cassandra DATE value.
> change DATE type to u32

- .github/workflows/build.yml
- CHANGELOG.md
- Cargo.toml
- README.md
Update repo location and author affiliation.
> Release 3.0.2
