- Cargo.toml
- src/cassandra/cluster.rs
Required so we can depend on our own forked version of the
low-level binding.
Will be restored to a versioned dependency once our
cassandra-sys-rs is on crates.io.
Because cassandra-sys-rs no longer exports a symbol (which we do not
in fact use), we should no longer export it either.
See https://github.com/Metaswitch/cassandra-sys-rs/pull/2 and
https://datastax-oss.atlassian.net/browse/CPP-473 for details.
> For now, use a git dependency on cassandra-sys-rs.

- README.md
When we published this crate to crates.io, we changed its name. We missed the references in the example (simple.rs) in the README, so it fails to compile.
This pull request fixes the readme to use the new crate name (and so fixes #12).
Signed-off-by: Angus Ireland <Angus.Ireland@metaswitch.com>
> Fix the crate name in the `extern`/`use` lines of the readme example.

- .travis.yml
Add code to CI script to enforce the presence of the `Signed-off-by:` line in all non-merge commits, as required by this repository's policy and explained in CONTRIBUTING.md.
> Verify that all new commits are signed off.

- src/cassandra/cluster.rs
- src/cassandra/log.rs
- src/cassandra/ssl.rs
- src/cassandra/util.rs
- src/lib.rs
- tests/types.rs
Exposes LogLevel, SslVerifyFlag, and CqlProtocolVersion more sensibly.
Notice that the SslVerifyFlags value is a set, and CqlProtocolVersion might as well just be an integer.
> Expose more enums

- Cargo.toml
- examples/disabled/logging.rs
- examples/schema_meta.rs
- examples/simple.rs
- src/cassandra/cluster.rs
- src/cassandra/column.rs
- src/cassandra/future.rs
- src/cassandra/log.rs
- src/cassandra/metrics.rs
- src/cassandra/session.rs
- src/cassandra/value.rs
- src/lib.rs
- tests/basic.rs
- tests/help/mod.rs
- tests/logging.rs
- tests/types.rs
As it says. Contact points should just be a string: no sense in converting to a Rust type and then back to a string again; we want the DNS and IPv6 behaviour of the underlying C++ library. There were some vestiges of old logging which are removed; this now adds proper structured logging using slog.
Also fixes or silences some warnings.
> Fix contact point handling and logging

- src/cassandra/batch.rs
- src/lib.rs
- tests/batch.rs
- tests/types.rs
Expose BatchType as a properly-wrapped type owned by cassandra-cpp, rather than directly as the underlying cassandra-cpp-sys type.
Exactly the same as, e.g., `Consistency`.
> Fix Cassandra BatchType

- Cargo.toml
- README.md
- src/cassandra/error.rs
Fix a bad docstring that tickled a compiler crash, bump the version, and update the README with a migration guide/changelog.
> Prepare release 0.9.0

- CONTRIBUTING.md
- Cargo.toml
Like it says. 
CONTRIBUTING guidelines: remind people to update CHANGELOG and the version in Cargo.toml as appropriate.
> Bump version for release; also document in CONTRIBUTING.

- CHANGELOG.md
- src/cassandra/inet.rs
- src/cassandra/tuple.rs
Happened to spot some brackets in the wrong place in the current implementation, making it nonsense.
Probably the relevant conversion didn't exist in the standard library when this code was written, but it does now so I've just used it.
> Fix conversion into Ipv6Addr

- CHANGELOG.md
- src/cassandra/statement.rs
- tests/basic.rs
Add wrapper for cass_statement_set_request_timeout. Styled on the similar wrapper for cass_cluster_set_request_timeout.
I cannot find any tests for similar functions in the code base, so I haven't added one for this, please let me know if there should be.
> Add statement request timeout wrapper

- src/cassandra/batch.rs
- src/cassandra/cluster.rs
- src/cassandra/data_type.rs
- src/cassandra/prepared.rs
- src/cassandra/row.rs
- src/cassandra/schema/aggregate_meta.rs
- src/cassandra/schema/column_meta.rs
- src/cassandra/schema/function_meta.rs
- src/cassandra/schema/keyspace_meta.rs
- src/cassandra/session.rs
- src/cassandra/ssl.rs
- src/cassandra/statement.rs
- src/cassandra/tuple.rs
- src/cassandra/user_type.rs
- src/cassandra/uuid.rs
When testing at load we discovered an intermittent `LIB_INDEX_OUT_OF_BOUNDS` errors, which we traced to `get_column_by_name` failing to identify a column which we knew was present in the row. Further investigation revealed that this was a use-after-free error in the unsafe code in this wrapper.
This test fixes the one that caused the problem, and also all other instances of the same pattern: passing `CString::new().as_ptr()` to a C function, which risks it being freed before the function is called. Instead we follow the `CString` docs and bind the `CString` to a local variable first.
Presumably this was exposed by a compiler upgrade.
> Fix unsafe lifetimes

- CHANGELOG.md
- src/cassandra/result.rs
- tests/batch.rs
- tests/bind_by_name.rs
Make iterator retain CassResult. Without this, if we free the iterator early all kinds of things go wrong.
This enables us to free CassResults when they are dropped (somewhat amazingly, this was disabled until now so we had a serious memory leak).
This resolves #35 .
Also fix up the CHANGELOG format to something modern while we're here.
> Make iterator retain CassResult.

- CHANGELOG.md
- src/cassandra/statement.rs
Fixes issues if you try to use the stmt macro without importing the Statement type.
Signed-off-by: Alex Parrill <aparrill@datto.com>
> Use absolute path in the stmt macro

- CHANGELOG.md
- src/cassandra/future.rs
The mutex guarding the future state must be unlocked *before* we free it; unlocking it after we free it somehow works with jemallocator but is obviously UB.
Resolves #53.
> Correct drop order for completed futures.

- CHANGELOG.md
- Cargo.toml
Release 0.14.0. Technically a breaking change because of the support for UDTs (the iterator item type was wrong).
> Bump version to 0.14.0.

- CHANGELOG.md
- src/cassandra/cluster.rs
This used a cassandra-sys type, `cass_bool_t`, which is not exposed to clients. Fix it to use a normal Rust boolean.
> Fix type signature on set_load_balance_dc_aware

- CHANGELOG.md
- src/cassandra/row.rs
- src/cassandra/statement.rs
- src/cassandra/uuid.rs
- tests/uuids.rs
This is a more efficient conversion than using strings between `CassUuid` and `Uuid` from the uuid crate. Also added `AsRustType<uuid::Uuid>` and `BindRustType<uuid:Uuid>` impls.
Resolves #56.
> More ergonomic uuid::Uuid handling

- CHANGELOG.md
- src/cassandra/prepared.rs
As per, https://datastax.github.io/cpp-driver/api/struct.CassPrepared/ a PreparedStatement is indeed Sync
> A prepared statement is read-only and it is thread-safe to concurrently bind new statements.
Fixes #72
(We have been running this change-set on prod for a few weeks now with no issue - so it's been empirically proven as well!)
> feat: PreparedStatement is Sync

- CHANGELOG.md
- src/cassandra/result.rs
- src/cassandra/statement.rs
`CassResult::set_paging_state_token` was simply not correct. It did nothing, and you cannot set a paging state token on a result, only on a statement. 
The underlying c ffi function `cass_result_paging_state_token` *returns* a paging state token by giving you a pointer to its data, and length.
I've modified this function to instead *copy* that value out, and return it as a `Vec<u8>`. I chose this instead of a `String` because, technically, paging state tokens do not have to be utf8 encoded.
In turn, I've also modified `set_paging_state_token` to take a `&[u8]` instead of `&str` to mirror the new implementation of `CassResult::paging_state_token` 
This PR supercedes #81 - which also contains an improper implementation.
> Properly implement paging state tokens.

- src/cassandra/statement.rs
- tests/basic.rs
The cassandra cpp driver ignores the value length parameter
and tries to find a null terminator in the passed string.
Worked around using `cass_statement_bind_bytes_by_name_n` which
is compatible and with string type and honor the value length
parameter.
> Workaround cpp driver string bind by name bug

- CHANGELOG.md
- Cargo.toml
- src/cassandra/future.rs
parking_lot::Mutex is faster than std::sync::Mutex, so let's use it for the critical lock in `CassFuture`.
This section of parking_lot's docs describes the difference: https://docs.rs/parking_lot/0.11.0/parking_lot/type.Mutex.html#differences-from-the-standard-library-mutex
> feat: use parking_lot::Mutex

- CHANGELOG.md
- src/cassandra/result.rs
we know the row count, so we can implement `size_hint` on `ResultIterator`, which will let various `collect` impl's be slightly more efficient.
> feat: implement `size_hint` on `ResultIterator`

- Cargo.toml
- src/cassandra/cluster.rs
- src/cassandra/iterator.rs
- src/cassandra/prepared.rs
- src/cassandra/schema/column_meta.rs
- src/cassandra/schema/function_meta.rs
- src/cassandra/schema/table_meta.rs
- src/cassandra/statement.rs
- src/cassandra/time.rs
- src/cassandra/value.rs
This PR removes a bunch of warnings, notably:
```
19 warning: unknown lint: `cast_possible_truncation`
12 warning: use of deprecated associated function `time::Duration::num_milliseconds`: Use the `whole_milliseconds` function. The value is clamped between `i64::min_value()` and `i64::max_value()`.
8 warning: use of deprecated associated function `time::Duration::num_seconds`: Use the `whole_seconds` function
4 warning: use of deprecated associated function `std::error::Error::description`: use the Display impl or to_string()
3 warning: unknown lint: `cast_sign_loss`
```
> chore: fix all warnings

- .travis.yml
- CHANGELOG.md
- src/cassandra/session.rs
- tests/batch.rs
- tests/logging.rs
- tests/paging.rs
`Session::execute_batch` and `Session::execute_batch_with_payloads` now take `&Batch` rather than `Batch`.
This was apparently an oversight in the original code; the parallel `execute` takes `&Statement` already.
This is a breaking change, but it's a straightforward fix: just add `&` to your argument list.
While we're here, fix a couple of warnings in test code related to printing panics, and remove travis-cargo (which was intermittently broken, and only used for coverage which we don't look at).
Fixes #118
> Batch execution no longer consumes the batch

- .github/workflows/build.yml
- CHANGELOG.md
- Cargo.toml
decimal by default pulls in various extra dependencies including the ancient rustc-serialize.
I can see that the project would like to reintroduce decimal support https://github.com/Metaswitch/cassandra-rs/issues/122 so I didnt outright remove this unused dep.
But maybe you would prefer me to just remove the dep so that decimal support can start from scratch and be free to choose a more up to date decimal crate?
> remove rustc-serialize from dependency tree

- .github/workflows/build.yml
Record the last missing DCO certification in the build script.
> Record DCO certification of remaining commit

- README.md
Just a minor change as I noticed the build status badge still pointed at Travis.
> Update build status badge URL in README.md

- CHANGELOG.md
- src/cassandra/inet.rs
The inet_str ends up being an `i8` due to type inference.
Attempting to store the bytes of a string in an i8 somehow manages to work most of the time but in rust 1.59 this broke in my application.
I fixed the issue by providing an array of the proper length to store the string bytes.
The test I added didnt pick up the issue in rust 1.59 (such is the nature of UB) but the fix does fix the issue in my application.
I would appreciate a patch release asap after this is merged.
> Fix UB in Inet::to_string

- CHANGELOG.md
- Cargo.toml
Release 0.17.2, and also tidy up Cargo.toml: remove traces of travis, and remove bizarre and unused dependency on clippy 0.0.
> Release 0.17.2

- .floki/Dockerfile
- CHANGELOG.md
- Cargo.toml
- README.md
This has been supported for some time; recognize that at last.
Also update floki file to match the GitHub actions file - use the required Cassandra driver version.
Also update CHANGELOG which was out of date.
> Release 1.0.0

- CHANGELOG.md
- Cargo.toml
- README.md
- src/cassandra/cluster.rs
- src/cassandra/result.rs
- src/cassandra/schema/table_meta.rs
- src/cassandra/ssl.rs
- src/cassandra/user_type.rs
- src/lib.rs
- tests/types.rs
This PR propagates the feature flag from https://github.com/Metaswitch/cassandra-sys-rs/pull/46 . I've added some test for this that don't pass automatically - since they need a custom compiled version of the Datastax driver - but they pass when you build and install the driver library in question.
> Add `early_access_min_tls_version` feature flag

- Cargo.toml
- src/cassandra/inet.rs
While i8 works fine on some platforms, ARM and some other places rely on
unsigned chars that libc provides
All the credit for the work done here goes to @stefanofranz, on PR #137 (for context, I copied his code, because the older PR was getting stale)
> fix ARM unsigned char (#137)

- src/cassandra/statement.rs
Although it isn't possible to get the tracing_id from a response yet, this small changes allows us to at least use the tracing flags in requests.
> Add set_tracing method

- Cargo.toml
- src/cassandra/log.rs
- src/lib.rs
- tests/logging.rs
My goal was actually to hook cassandra-rs up to tracing rather than the log crate.
However doing that proved to be incredibly complex.
tracing does a lot of crazy compile time magic to make it go fast, so converting runtime log data provided by the cpp data to tracing's format is really tricky, if you want to see what I mean just take a look at the implementations of tracing-slog or tracing-log.
I also tried using the tracing-slog crate with cassandra-rs's slog support but that maps very poorly to tracing: https://docs.rs/tracing-slog/latest/tracing_slog/
On the other hand the tracing log crate https://docs.rs/tracing-log/latest/tracing_log/ works really well, so the solution I settled for was implementing log for cassandra-rs and using tracing-log to convert that to tracing.
This also …
> Add support for logging via the log crate

- .github/workflows/build.yml
- CHANGELOG.md
- src/cassandra/error.rs
- src/cassandra/future.rs
- src/cassandra/inet.rs
- src/cassandra/iterator.rs
- src/cassandra/prepared.rs
- src/cassandra/result.rs
- src/cassandra/schema/aggregate_meta.rs
- src/cassandra/schema/column_meta.rs
- src/cassandra/schema/function_meta.rs
- src/cassandra/schema/keyspace_meta.rs
- src/cassandra/schema/table_meta.rs
- src/cassandra/uuid.rs
- src/cassandra/value.rs
std::mem::zeroed is unsafe so the less times we call it, the easier it is to reason about the correctness of our code. (One less invariant to keep in our head)
A good example of this going wrong was: https://github.com/Metaswitch/cassandra-rs/pull/133
This PR should cause no functional changes, all the code it replaces is correct and was not invoking any UB. The goal is just to make our unsafe usage easier to audit for correctness.
The one exception to this is `Inet::default()` but this was not changed to fix UB but to give a semantically correct default value.
> Remove all instances of mem::zeroed

- CHANGELOG.md
- src/cassandra/cluster.rs
Expose the `set_exponential_reconnect` function. Working on testing this at the moment.
This is the default policy (as per the Note in https://docs.datastax.com/en/dev-app-drivers/docs/reconnectionPolicies.html), but exposing it here makes the timings configurable.
Note that the default max delay is actually 600000ms (10 minutes), not 60000ms (1 minute) - the documentation is wrong. The docstring I added for the rust wrapper fixes this error.
c.f. the constant in the C++ driver: https://github.com/datastax/cpp-driver/blob/7f193cb347948b79b1eadf44c8235ee04d66f3cf/src/constants.hpp#L127
> Expose set_exponential_reconnect function

- .github/workflows/build.yml
- scripts/cassandra-cpp-driver.control
- scripts/install_ubuntu_packages.sh
- tests/basic.rs
Same as https://github.com/Metaswitch/cassandra-sys-rs/pull/50
I also noticed we were missing `cargo fmt` on this repo so I copied that over.
> future proof ci

- src/cassandra/cluster.rs
Hello.
I try to build multi-thread tokio runtime and https://github.com/swizard0/ero
I have a compiler error
```rust
error: future cannot be sent between threads safely
--> src/main.rs:49:41
|
49  |       supervisor_pid.spawn_link_permanent(cassandra_server.run(
|  _________________________________________^
50  | |         supervisor_server.pid(),
51  | |         3,
52  | |         core_params.cassandra,
53  | |     ));
| |_____^ future is not `Send`
|
= help: within `impl Future<Output = ()>`, the trait `Send` is not implemented for `*const i8`
note: future is not `Send` as this value is used across an await
--> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cassandra-cpp-2.0.0/src/cassandra/cluster.rs:222:23
|
212 |         let keyspace_ptr = keyspace.as_ptr() as *const …
```
> reorder lines in Cluster::connect_keyspace

- examples/collections.rs
- src/cassandra/cluster.rs
- src/cassandra/custom_payload.rs
- src/cassandra/future.rs
- src/cassandra/inet.rs
- src/cassandra/result.rs
- src/cassandra/session.rs
- src/cassandra/ssl.rs
- src/cassandra/uuid.rs
- src/cassandra/value.rs
- src/lib.rs
- tests/basic.rs
- tests/logging.rs
- tests/maps.rs
- tests/paging.rs
- tests/types.rs
- tests/uuids.rs
A lot of these are super minor, but a few are important like the missing awaits in `tests/basic.rs`
Happy to remove all the minor stuff to land the important ones, but the minor stuff was really easy to do, just: `cargo clippy --fix`
> Fix some warnings from rustc and clippy

- CHANGELOG.md
- Cargo.toml
I'm treating the first fix as a bugfix and not bumping the minor version, even though technically it's an API change (adding back `Send`).
> Release 2.0.1

- .github/workflows/build.yml
Add a button to manually trigger the build workflow, per https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow#configuring-a-workflow-to-run-manually
> Enable manual workflow trigger

- Cargo.toml
- src/cassandra/row.rs
- src/cassandra/statement.rs
- src/cassandra/value.rs
- tests/basic.rs
Get cassadra decimal value as BigDecimal (https://docs.rs/bigdecimal/latest/bigdecimal/)
Signed-off-by: Marian Marencik <github@marianm.net>
> Add get_decimal()

- src/cassandra/row.rs
It seems like this was missed in https://github.com/Metaswitch/cassandra-rs/commit/299e6ac50f87eb2823a373baec37b590a74994ee
> Make Row::iter public

- Cargo.toml
Also take opportunity to fix up authors:
Tupshin hasn't been involved since the fork and this has evolved greatly since then.
Also update my email address to reflect my current employer (Microsoft); Metaswitch is a brand of Microsoft.
> Bump to v3.0.2-pre and update authors
